[project]
name = "lux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "g4f[all]>=0.4.8.6",
    "pillow>=11.1.0",
    "pytesseract>=0.3.13",
    "sqlalchemy>=2.0.39",
]
