[project]
name = "lux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.11",
    "g4f[all]>=0.4.8.5",
    "sqlalchemy>=2.0.39",
]
